

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

dist: jammy

cache: pip

services:
  - xvfb

python:
  - "3.12"

install:
  - sudo apt update
  - sudo apt install libnotify-dev
  - sudo apt install libgtk-3-dev
  - sudo apt-get install -y  libsdl2-dev
  - GLOBAL=`python --version`
  - echo $GLOBAL
  - PY_VERSION=${GLOBAL#* }
  - pyenv global ${PY_VERSION}
  - pip install --upgrade pip
  - pip install wheel
  - pip install setuptools
  - pip install six==1.16.0
  - pip install html-testRunner
  - pip install attrdict3
  - pip install wxPython
  - pip install antlr4-python3-runtime==4.13.1
  - pip install codeallybasic==1.8.0
  - pip install codeallyadvanced==1.3.3
  - pip install pyimage2pdf==1.0.2
  - pip install pyutmodelv2==2.2.2
  - pip install ogl==3.6.2
  - pip install oglio==2.3.4
  - pip install buildlackey~=1.7.0
  - pip install orthogonal==1.3.1
  - pip install pyumldiagrams==3.1.20
  - pip install pyforcedirectedlayout>=0.80.5
  - pip install pyorthogonalrouting==1.3.0

# command to run tests
script:
  - unittests
