
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install library dependencies
          command: |
            sudo apt update
            sudo apt install libnotify-dev
            sudo apt install libgtk-3-dev
            sudo apt-get install -y  libsdl2-dev
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install six==1.16.0
            pip install html-testRunner
            pip install attrdict3
            pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04  wxPython
            pip install antlr4-python3-runtime==4.11.1
            pip install networkx==3.0
            pip install orthogonal==1.2.0
            pip install pyumldiagrams==3.1.0
            pip install codeallybasic==0.5.2
            pip install codeallyadvanced==0.5.2
            pip install pyutmodelv2==2.0.0a6
            pip install ogl==2.0.0a6
            pip install untanglepyut==2.0.0a6
            pip install oglio==2.0.0a6
            pip install buildlackey~=1.6.2
      - run:
            name: run tests
            command: | 
              runtests