
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyutplugins.preferences.PluginPreferences import DEFAULT_MERMAID_DIRECTION
from pyutplugins.preferences.PluginPreferences import DEFAULT_ORTHOGONAL_LAYOUT_SIZE
from pyutplugins.preferences.PluginPreferences import PluginPreferences

from pyutplugins.toolplugins.orthogonal.LayoutAreaSize import LayoutAreaSize

from pyutplugins.ioplugins.mermaid.MermaidDirection import MermaidDirection


class TestPyutPreferences(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 07 January 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testInstantiation(self):

        preferences: PluginPreferences = PluginPreferences()

        self.assertIsNotNone(preferences, "Where is my object !!")

    def testLayoutDeserializer(self):

        preferences: PluginPreferences = PluginPreferences()

        saveValue: LayoutAreaSize = preferences.orthogonalLayoutSize

        preferences.orthogonalLayoutSize = DEFAULT_ORTHOGONAL_LAYOUT_SIZE

        actualValue: LayoutAreaSize = preferences.orthogonalLayoutSize

        self.assertEqual(DEFAULT_ORTHOGONAL_LAYOUT_SIZE, actualValue, 'Hmm did not work')

        preferences.orthogonalLayoutSize = saveValue.__str__()

    def testMermaidLayoutDeserializer(self):
        preferences: PluginPreferences = PluginPreferences()

        saveValue: MermaidDirection = preferences.mermaidLayoutDirection

        preferences.mermaidLayoutDirection = DEFAULT_MERMAID_DIRECTION

        actualValue: MermaidDirection = preferences.mermaidLayoutDirection

        self.assertEqual(actualValue, DEFAULT_MERMAID_DIRECTION, 'Not set or retrieved correctly')

        preferences.mermaidLayoutDirection = saveValue


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestPyutPreferences))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
