graph [
	directed 1
	version  1.0
	label "GML for DefaultGraphName"
	comment "Generated by GML Exporter Version 1.0.0"
	node [
		id 10000
		label "ClassName_10000"
		graphics [
			x 100.0
			y 100.0
			z 0
			w 50.0
			h 50.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
	node [
		id 10010
		label "ClassName_10010"
		graphics [
			x 175.0
			y 200.0
			z 0
			w 50.0
			h 50.0
			d 0
			type "rectangle"
			width 0.12
			fill "#ff0000"
			outline "#000000"
		]
	]
]